artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_path: data/customer_shopping_data.csv
  ingested_data_path: artifacts/data_ingestion/data.csv

data_validation:
  root_dir: artifacts/data_validation
  validation_status_file: artifacts/data_validation/status.txt
  required_columns: ["invoice_no", "customer_id", "gender", "age", "category", "quantity", "price", "payment_method", "invoice_date", "shopping_mall"]
  column_schemas:
    invoice_no: "object"
    customer_id: "object"
    gender: "object"
    age: "int64"
    category: "object"
    quantity: "int64"
    price: "float64"
    payment_method: "object"
    invoice_date: "object" 
    shopping_mall: "object"

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv  
  transformed_data_path: artifacts/data_transformation/rfm_data.csv
  scaler_path: artifacts/models/scaler.dill

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/rfm_data.csv
  model_path: artifacts/models/model.dill
  model_name: "kmeans"

  params:
    n_clusters: 5       
    init: "k-means++"
    random_state: 42
  

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/models/model.dill
  scaler_path: artifacts/models/scaler.dill
  data_path: artifacts/data_transformation/rfm_data.csv
  metrics_file_path: artifacts/model_evaluation/metrics.json
  silhouette_plot_path: artifacts/model_evaluation/silhouette_plot.png