artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_path: data/Online_Retail.xlsx
  ingested_data_path: artifacts/data_ingestion/data.csv

data_validation:
  root_dir: artifacts/data_validation
  data_path: artifacts/data_ingestion/data.csv
  validation_status_file: artifacts/data_validation/status.txt
  required_columns: ["InvoiceNo", "StockCode", "Description", "Quantity", "InvoiceDate", "UnitPrice", "CustomerID", "Country"]
  column_schemas:
    InvoiceNo: "object"
    StockCode: "object"
    Description: "object"
    Quantity: "int64"
    InvoiceDate: "object" 
    UnitPrice: "float64"
    CustomerID: "float64" 
    Country: "object"

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv  
  transformed_data_path: artifacts/data_transformation/rfm_data.csv
  scaler_path: artifacts/models/scaler.dill

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/rfm_data.csv
  model_path: artifacts/models/model.dill
  model_name: "sc"

  params:
    num_clusters: 4      
     

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/models/model.dill
  scaler_path: artifacts/models/scaler.dill
  data_path: artifacts/data_transformation/rfm_data.csv
  metrics_file_path: artifacts/model_evaluation/metrics.json
  silhouette_plot_path: artifacts/model_evaluation/silhouette_plot.png